### ISSUE TITLE
How do I setup the mod?

### ISSUE THREAD

**Issue by Eatham532** [devOS-Sanity-Edition/TeaBridge#10]
My server can't start. It seems I have not setup the mod correctly.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'teabridge'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.14.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.14.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.14.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.14.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.14.jar:?]
at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.14.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.14.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric.jar:0.11.1]
Caused by: java.lang.NoSuchFieldError: Companion
at okhttp3.internal.Util.<clinit>(Util.kt:70) ~[com_squareup_okhttp3_okhttp-4.9.3-d6632456a0ebcb78.jar:?]
at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.kt:243) ~[com_squareup_okhttp3_okhttp-4.9.3-d6632456a0ebcb78.jar:?]
at okhttp3.Dispatcher.setMaxRequestsPerHost(Dispatcher.kt:71) ~[com_squareup_okhttp3_okhttp-4.9.3-d6632456a0ebcb78.jar:?]
at net.dv8tion.jda.internal.utils.IOUtil.newHttpClientBuilder(IOUtil.java:107) ~[net_dv8tion_jda-5.0.0-beta.2-a006176233bb5efb.jar:?]
at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1762) ~[net_dv8tion_jda-5.0.0-beta.2-a006176233bb5efb.jar:?]
at one.devos.nautical.teabridge.discord.Discord.start(Discord.java:51) ~[TeaBridge-1.0.2.jar:?]
at one.devos.nautical.teabridge.TeaBridge.initialize(TeaBridge.java:35) ~[TeaBridge-1.0.2.jar:?]
at one.devos.nautical.teabridge.PlatformUtil.onInitializeServer(PlatformUtil.java:43) ~[TeaBridge-1.0.2.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.14.jar:?]
... 8 more
```

This is how I setup my config
```
{
  "discord": {
    "token": "My discord bot token",
    "guild": "My Discord Server ID",
    "channel": "My Channel ID",
    "webhook": "My Webhook token"
  },
  "game": {
    "serverStartingMessage": "Server is starting...",
    "serverStartMessage": "Server has started!",
    "serverStopMessage": "Server has stopped!",
    "serverCrashMessage": "Server has crashed!",
    "mirrorDeath": true,
    "mirrorAdvancements": true
  },
  "crashes": {
    "uploadToMclogs": true
  }
}```

Also, you might want a better way to tell the user what is wrong. Like a message saying that the bot Id is incorrect

**Comment by asoji** [comment]
Half a year late [sorry!] but install the Fabric Language Kotlin mod
